version : "3"
services:
  ut-web:
    build:
      context: .
      dockerfile: dockerfiles/Web.Dockerfile
    container_name: ut-web
    depends_on:
      - ut-web-pg
    volumes:
      - .:/var/www/html
    restart: always
    ports:
      - "2001:80"
    environment:
      APP_NAME: "Web boilerplate"
    networks:
      ut-web-network:
        ipv4_address: 200.21.1.1
    extra_hosts:
      - host.docker.internal:host-gateway

  ut-web-pg:
    image: postgres:15
    container_name: ut-web-pg
    volumes:
      - ut-web-pg-disk:/var/lib/postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: testing
    networks:
      ut-web-network:
        ipv4_address: 200.21.1.2

  ut-web-q:
    build:
      context: .
      dockerfile: dockerfiles/QueueListener.Dockerfile
    container_name: ut-web-q
    depends_on:
      - ut-web
    volumes:
      - .:/var/www/html
    restart: unless-stopped
    networks:
      ut-web-network:
        ipv4_address: 200.21.1.3

  ut-web-mailpit:
    image: 'axllent/mailpit:latest'
    container_name: ut-web-mailpit
    restart: always
    networks:
      ut-web-network:
        ipv4_address: 200.21.1.4

  ut-web-0x:
    build:
      context: .
      dockerfile: dockerfiles/SansXdebug.Dockerfile
    container_name: ut-web-0x
    depends_on:
      - ut-web
    volumes:
      - .:/var/www/html
    restart: always
    networks:
      ut-web-network:
        ipv4_address: 200.21.1.5

  ut-web-fe:
    build:
      context: .
      dockerfile: dockerfiles/Fe.Dockerfile
    container_name: ut-web-fe
    ports:
      - "2007:5173"
    depends_on:
      - ut-web
    volumes:
      - .:/var/www/html
    restart: unless-stopped
    networks:
      ut-web-network:
        ipv4_address: 200.21.1.6

# On-disk storage of DB data, when containers are stopped
volumes:
  ut-web-pg-disk: {}

# Local network for services running using this docker-compose config
networks:
  ut-web-network:
    ipam:
      driver: default
      config:
        - subnet: 200.21.0.0/16
